# Form implementation generated from reading ui file 'ui_auth.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(191, 191)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 191))
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 191, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_lbl = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_lbl.sizePolicy().hasHeightForWidth())
        self.login_lbl.setSizePolicy(sizePolicy)
        self.login_lbl.setMinimumSize(QtCore.QSize(0, 16))
        self.login_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.login_lbl.setObjectName("login_lbl")
        self.verticalLayout.addWidget(self.login_lbl)
        self.login = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.login.setMinimumSize(QtCore.QSize(0, 21))
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.pass_lbl = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pass_lbl.sizePolicy().hasHeightForWidth())
        self.pass_lbl.setSizePolicy(sizePolicy)
        self.pass_lbl.setMinimumSize(QtCore.QSize(0, 16))
        self.pass_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.pass_lbl.setObjectName("pass_lbl")
        self.verticalLayout.addWidget(self.pass_lbl)
        self.password = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.password.setMinimumSize(QtCore.QSize(0, 21))
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.sign_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.sign_btn.setMinimumSize(QtCore.QSize(0, 41))
        self.sign_btn.setObjectName("sign_btn")
        self.verticalLayout.addWidget(self.sign_btn)
        self.reg_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.reg_btn.setMinimumSize(QtCore.QSize(0, 26))
        self.reg_btn.setObjectName("reg_btn")
        self.verticalLayout.addWidget(self.reg_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Авторизация"))
        self.login_lbl.setText(_translate("Form", "Логин"))
        self.pass_lbl.setText(_translate("Form", "Пароль"))
        self.sign_btn.setText(_translate("Form", "Войти"))
        self.reg_btn.setText(_translate("Form", "Зарегистрироваться"))
